name: ELASPY
channels:
  - https://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
dependencies:
  - pluggy=1.0.0
  - numpy=1.23.1
  - spyder
  - python=3.10.8
  - simpy=4.0.1
  - sphinx=5.0.2
  - mypy=0.981
  - pulp=2.7.0
  - pytest=7.3.1
  - pandas=1.4.4
  - matplotlib=3.5.2
  - scipy=1.9.3
  - pydata-sphinx-theme=0.15.3
  - conda-forge::sphinx-design=0.6.0
  - pip=24.0
  - pip:
    - sphinx-favicon==1.0.1